In [7]:
def get_data(table):
    
    conn = None
    params = {
        'host': 'localhost',
        'database': 'preds',
        'user': 'postgres',
        'password': 'pass',
        'port': '5432'
    }
    
    try:
        conn = psycopg2.connect(**params)
    
        query = """
        SELECT *
        FROM {}
        """.format(table)
    
        df = pd.read_sql_query(query, conn)
        
        return df
    except Exception as e:
        return e
    finally:
        if conn is not None:
            conn.close()

In [10]:
import psycopg2
import pandas as pd

tables = ['countries', 
          'leagues', 
          'teams',
          'team_stats',
          'fixtures',
          'fixture_stats',
          'players',
          'player_stats',
          'fixtures_updated',
          'predictions']
big_df = {}

df_0 = get_data(tables[0])
df_1 = get_data(tables[1])
df_2 = get_data(tables[2])
df_3 = get_data(tables[3])
df_4 = get_data(tables[4])
df_5 = get_data(tables[5])
df_6 = get_data(tables[6])
df_7 = get_data(tables[7])
df_8 = get_data(tables[8])
df_9 = get_data(tables[9])

C:\Users\olows\AppData\Local\Temp\ipykernel_10476\3797080077.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)
C:\Users\olows\AppData\Local\Temp\ipykernel_10476\3797080077.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)
C:\Users\olows\AppData\Local\Temp\ipykernel_10476\3797080077.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

IndexError: list index out of range

In [18]:
def insert_table(table_name, df):
    conn = None
    cur = None
    params = {
        'host': 'localhost',
        'database': 'preds',
        'user': 'postgres',
        'password': 'pass',
        'port': '5432'
    }
    try:
        # Establish the connection
        conn = psycopg2.connect(**params)
        cur = conn.cursor()
        
        #insert data into tables
        insert_query = """
            INSERT INTO {} ({})
            VALUES ({})
        """.format(table_name, ','.join(df.columns), ','.join(['%s']*len(df.columns)))
        cur.executemany(insert_query, df.values.tolist())
        print(f'table {table_name} updated')
        
        # Commit the changes
        conn.commit()
        
    except Exception as e:
        print(e)
    finally:
        if conn is not None:
            # Close the cursor and connection
            cur.close()
        if cur is not None:
            conn.close()

In [19]:
insert_table('countries', df_0)
insert_table('leagues', df_1)
insert_table('teams', df_2)
insert_table('team_stats', df_3)
insert_table('fixtures', df_4)
insert_table('fixture_stats', df_5)
insert_table('players', df_6)
insert_table('player_stats', df_7)
insert_table('fixtures_updated', df_8)
insert_table('predictions', df_9)

table countries updated
table leagues updated
table teams updated
insert or update on table "team_stats" violates foreign key constraint "fk_stats_team"
DETAIL:  Key (team_id)=(18123) is not present in table "teams".

insert or update on table "fixtures" violates foreign key constraint "fk_fixture_team_away_id"
DETAIL:  Key (teams_away_id)=(103) is not present in table "teams".

'DatabaseError' object has no attribute 'columns'
table players updated
table player_stats updated
table fixtures_updated updated
column "home_over_3_prob" of relation "predictions" does not exist
LINE 2: ...d,teams_away_id,home_over_1_prob,home_over_2_prob,home_over_...
                                                             ^

In [28]:
df_4[df_4['league_id']==334]

,fixture_id,fixture_referee,fixture_date,fixture_venue_id,fixture_status_long,fixture_status_short,fixture_status_elapsed,league_id,league_season,league_round,...,goals_home,goals_away,score_halftime_home,score_halftime_away,score_fulltime_home,score_fulltime_away,score_extratime_home,score_extratime_away,score_penalty_home,score_penalty_away
446194,496399,A. Kutakov,2011-07-16,2436,Match Finished,FT,90,334,2011,Regular Season - 1,...,0,1,0,1,0,1,0,0,0,0
446195,496400,O. Bondar,2011-07-16,2431,Match Finished,FT,90,334,2011,Regular Season - 1,...,1,2,0,0,1,2,0,0,0,0
446196,496401,S. Skrypak,2011-07-16,19517,Match Finished,FT,90,334,2011,Regular Season - 1,...,0,1,0,0,0,1,0,0,0,0
446197,496402,K. Trukhanov,2011-07-16,8320,Match Finished,FT,90,334,2011,Regular Season - 1,...,2,2,2,0,2,2,0,0,0,0
446198,496403,I. Lavriv,2011-07-16,4761,Match Finished,FT,90,334,2011,Regular Season - 1,...,1,1,1,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447281,495848,R. Kalyta,2015-06-03,2434,Match Finished,FT,90,334,2014,Regular Season - 30,...,5,1,4,1,5,1,0,0,0,0
447282,495849,V. Kopievskiy,2015-06-03,0,Match Finished,FT,90,334,2014,Regular Season - 30,...,1,0,0,0,1,0,0,0,0,0
447283,495850,D. Kryvushkin,2015-06-03,6338,Match Finished,FT,90,334,2014,Regular Season - 30,...,1,2,0,0,1,2,0,0,0,0
447284,495851,O. Dedov,2015-06-03,2431,Match Finished,FT,90,334,2014,Regular Season - 30,...,0,1,0,0,0,1,0,0,0,0
447285,495852,M. Kryvonosov,2015-06-03,8317,Match Finished,FT,90,334,2014,Regular Season - 30,...,1,1,1,1,1,1,0,0,0,0

In [29]:
df_4

,fixture_id,fixture_referee,fixture_date,fixture_venue_id,fixture_status_long,fixture_status_short,fixture_status_elapsed,league_id,league_season,league_round,...,goals_home,goals_away,score_halftime_home,score_halftime_away,score_fulltime_home,score_fulltime_away,score_extratime_home,score_extratime_away,score_penalty_home,score_penalty_away
0,710556,M. Oliver,2021-08-13,10503,Match Finished,FT,90,39,2021,Regular Season - 1,...,2,0,1,0,2,0,0,0,0,0
1,710557,D. Coote,2021-08-14,512,Match Finished,FT,90,39,2021,Regular Season - 1,...,1,2,1,0,1,2,0,0,0,0
2,710558,J. Moss,2021-08-14,519,Match Finished,FT,90,39,2021,Regular Season - 1,...,3,0,2,0,3,0,0,0,0,0
3,710559,A. Madley,2021-08-14,8560,Match Finished,FT,90,39,2021,Regular Season - 1,...,3,1,0,1,3,1,0,0,0,0
4,710560,C. Pawson,2021-08-14,547,Match Finished,FT,90,39,2021,Regular Season - 1,...,1,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447281,495848,R. Kalyta,2015-06-03,2434,Match Finished,FT,90,334,2014,Regular Season - 30,...,5,1,4,1,5,1,0,0,0,0
447282,495849,V. Kopievskiy,2015-06-03,0,Match Finished,FT,90,334,2014,Regular Season - 30,...,1,0,0,0,1,0,0,0,0,0
447283,495850,D. Kryvushkin,2015-06-03,6338,Match Finished,FT,90,334,2014,Regular Season - 30,...,1,2,0,0,1,2,0,0,0,0
447284,495851,O. Dedov,2015-06-03,2431,Match Finished,FT,90,334,2014,Regular Season - 30,...,0,1,0,0,0,1,0,0,0,0
447285,495852,M. Kryvonosov,2015-06-03,8317,Match Finished,FT,90,334,2014,Regular Season - 30,...,1,1,1,1,1,1,0,0,0,0