In [ ]:
def get_data(endpoint, params):
    
    URL = "https://v3.football.api-sports.io/"
    headers = {
	'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key': "fb2140228973d644db847895c454c22b"
    }
    
    response = requests.get(
        URL+endpoint,
        headers = headers,
        params = params
    )
    if response.status_code == 200:
            
        remaining = response.headers.get("x-ratelimit-requests-remaining")
        data = response.json()
        print(f"requests before reaching limit {remaining}")

    else:
        print(f"Error {response.status_code}, {response.text}")

    return data, remaining

In [ ]:
def encode_data(data_dict, parent_key = '', sep= '_'):
    encoded = []
    for key, val in data_dict.items():
        new_key = f'{parent_key}{sep}{key}' if parent_key else key
        if isinstance(val, dict):
            encoded.extend(encode_data(val, new_key, sep=sep).items())
        elif isinstance(val, list):
            if val:
                if all(isinstance(i, dict) for i in val):
                    for k, v in enumerate(val):
                        v_key = f'{new_key}{sep}{k}'
                        encoded.extend(encode_data(v, v_key, sep=sep).items())
                else:
                    encoded.append((new_key, val))
            else:
                encoded.append((new_key, []))
        else:
            encoded.append((new_key, val))
    return dict(encoded)

In [ ]:
def data_to_sql(table_name, df, pg_hook, conflict_columns, update_columns = None):
    conn = None
    cur = None
    try:
        # Establish the connection
        conn = pg_hook.get_conn()
        cur = conn.cursor()

        #insert data into tables
        if len(conflict_columns) == 0:
            insert_query = """
                INSERT INTO {} ({})
                VALUES ({})
            """.format(table_name, ','.join(df.columns), ','.join(['%s']*len(df.columns)))
        else:
            if update_columns:
                update_set = ', '.join([f"{col} = EXCLUDED.{col}" for col in update_columns])
                insert_query = """
                    INSERT INTO {} ({})
                    VALUES ({})
                    ON CONFLICT ({}) DO UPDATE SET {}
                """.format(table_name, ','.join(df.columns), ','.join(['%s']*len(df.columns)), ','.join(conflict_columns), update_set)

            else:
                insert_query = """
                    INSERT INTO {} ({})
                    VALUES ({})
                    ON CONFLICT ({}) DO NOTHING
                """.format(table_name, ','.join(df.columns), ','.join(['%s']*len(df.columns)), ','.join(conflict_columns))
        cur.executemany(insert_query, df.values.tolist())
        print(f'table {table_name} updated')
        
        # Commit the changes
        conn.commit()
        
    except Exception as e:
        print(f"Error: {e}")
        if conn is not None:
            conn.rollback()
    finally:
        if conn is not None:
            # Close the cursor and connection
            cur.close()
        if cur is not None:
            conn.close()

In [14]:
from datetime import date
import datetime
import pandas as pd

today = date.today()
es = pd.read_csv('data/european_seasons.csv')
s = pd.read_csv('data/seasons.csv')
seasons = pd.merge(es,s[['league_id','year','start','end']], on = ['league_id', 'year'])
seasons['start'] = pd.to_datetime(seasons['start']).dt.date
seasons['end'] = pd.to_datetime(seasons['end']).dt.date

In [22]:
current_seasons = seasons[(seasons['start']<today)&(seasons['end']>today)][['league_id', 'year']]
to_get = current_seasons.values.tolist()

In [9]:
remaining = 100
done = False
fix_data = []

path = 'data/last.json'
with open(path, 'r') as file:
    last = json.load(file)

if not last[2]:
    ind = to_get.index([last[0], last[1])
    to_get = to_get[ind:]

while (remaining > 0)&(done == False):
    params = {'league' : to_get[0][0], 'year': to_get[0][1]}
    data, remaining = get_data('fixtures', params)
    remaining = int(remaining)
    if len(data['response'])>0:
        fix_data.extend(encode_data(fix) for fix in data['response'])
    
    to_get.pop(0)
    if len(to_get) == 0:
        done = True

if remaining <= 0 and not done:
    last = [to_get[0][0],to_get[0][1], done]
    path = 'data/last.json'
    with open(path, 'w') as file:
        json.dump(last, file)

if len(fix_data) > 0:
    send_to_sql()

,Unnamed: 0,league_id,name,country,year,players,statistics_fixtures,current,predictions,odds,start,end
0,0,39,Premier League,England,2010,True,False,False,True,False,2010-08-14,2011-05-17
1,1,39,Premier League,England,2011,True,False,False,True,False,2011-08-13,2012-05-13
2,2,39,Premier League,England,2012,True,False,False,True,False,2012-08-18,2013-05-19
3,3,39,Premier League,England,2013,True,False,False,True,False,2013-08-17,2014-05-11
4,4,39,Premier League,England,2014,True,True,False,True,False,2014-08-16,2015-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,3195,837,Rock Cup,Gibraltar,2020,False,False,False,True,False,2021-04-06,2021-05-19
3196,3196,837,Rock Cup,Gibraltar,2022,False,False,False,True,False,2022-02-05,2022-05-07
3197,3197,837,Rock Cup,Gibraltar,2023,False,False,False,True,False,2023-01-16,2023-04-27
3198,3198,837,Rock Cup,Gibraltar,2024,False,False,True,True,False,2024-01-30,2024-04-17
3199,3199,1042,Super Cup,Gibraltar,2023,False,False,True,True,False,2023-09-15,2023-09-15